EjemploAplicacionWeb/EjemploAplicacionWeb/Controllers/AsignaPlazasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using libNominaCurso;

namespace EjemploAplicacionWeb.Controllers
{
    public class AsignaPlazasController : Controller
    {
        private CodeFirstContexto db = new CodeFirstContexto();

        // GET: AsignaPlazas
        public ActionResult Index()
        {
            var asignacionesPlaza = db.AsignacionesPlaza.Include(a => a.oEmpleado).Include(a => a.oPlaza);
            return View(asignacionesPlaza.ToList());
        }

        // GET: AsignaPlazas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AsignaPlaza asignaPlaza = db.AsignacionesPlaza.Find(id);
            if (asignaPlaza == null)
            {
                return HttpNotFound();
            }
            return View(asignaPlaza);
        }

        // GET: AsignaPlazas/Create
        public ActionResult Create()
        {
            ViewBag.EmpleadoId = new SelectList(db.Empleados, "EmpleadoId", "Nombres");
            ViewBag.PlazaId = new SelectList(db.Plazas, "PlazaId", "NombrePlaza");
            return View();
        }

        // POST: AsignaPlazas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AsignaPlazaId,FechaInicio,FechaFinal,EmpleadoId,PlazaId")] AsignaPlaza asignaPlaza)
        {
            if (ModelState.IsValid)
            {
                db.AsignacionesPlaza.Add(asignaPlaza);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.EmpleadoId = new SelectList(db.Empleados, "EmpleadoId", "Nombres", asignaPlaza.EmpleadoId);
            ViewBag.PlazaId = new SelectList(db.Plazas, "PlazaId", "NombrePlaza", asignaPlaza.PlazaId);
            return View(asignaPlaza);
        }

        // GET: AsignaPlazas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AsignaPlaza asignaPlaza = db.AsignacionesPlaza.Find(id);
            if (asignaPlaza == null)
            {
                return HttpNotFound();
            }
            ViewBag.EmpleadoId = new SelectList(db.Empleados, "EmpleadoId", "Clave", asignaPlaza.EmpleadoId);
            ViewBag.PlazaId = new SelectList(db.Plazas, "PlazaId", "Clave", asignaPlaza.PlazaId);
            return View(asignaPlaza);
        }

        // POST: AsignaPlazas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AsignaPlazaId,FechaInicio,FechaFinal,EmpleadoId,PlazaId")] AsignaPlaza asignaPlaza)
        {
            if (ModelState.IsValid)
            {
                db.Entry(asignaPlaza).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EmpleadoId = new SelectList(db.Empleados, "EmpleadoId", "Clave", asignaPlaza.EmpleadoId);
            ViewBag.PlazaId = new SelectList(db.Plazas, "PlazaId", "Clave", asignaPlaza.PlazaId);
            return View(asignaPlaza);
        }

        // GET: AsignaPlazas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AsignaPlaza asignaPlaza = db.AsignacionesPlaza.Find(id);
            if (asignaPlaza == null)
            {
                return HttpNotFound();
            }
            return View(asignaPlaza);
        }

        // POST: AsignaPlazas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AsignaPlaza asignaPlaza = db.AsignacionesPlaza.Find(id);
            db.AsignacionesPlaza.Remove(asignaPlaza);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EjemploAplicacionWeb/EjemploAplicacionWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nomina de Curso", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                <a href="http://www.expea.mx"><img src="~/imgs/Expea4.png" width="123" height="40" alt="Logo expea" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Empleados", "Busca", "Empleados")</li>
                    <li>@Html.ActionLink("Plazas", "Index", "Plazas")</li>
                    <li>@Html.ActionLink("Asignaciones de Plaza", "Index", "AsignaPlazas")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

EjemploAplicacionWeb/EjemploAplicacionWeb/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nomina de Curso", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Empleados", "Busca", "Empleados")</li>
                    <li>@Html.ActionLink("Plazas", "Index", "Plazas")</li>
                    <li>@Html.ActionLink("Asignaciones de Plaza", "Index", "AsignaPlazas")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>