EjemploAplicacionWeb/EjemploAplicacionWeb/Controllers/BeneficiariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using libNominaCurso;

namespace EjemploAplicacionWeb.Controllers
{
    public class BeneficiariosController : Controller
    {
        private CodeFirstContexto db = new CodeFirstContexto();

        // GET: Beneficiarios/Create
        public ActionResult Create(int id)
        {
            Beneficiario beneficiario = new Beneficiario();
            beneficiario.EmpleadoId = id;
            return PartialView("_CreaBeneficiario", beneficiario);
        }

        // POST: Beneficiarios/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BeneficiarioId,NombreCompleto,Porcentaje,EmpleadoId")] Beneficiario beneficiario)
        {
            if (ModelState.IsValid)
            {
                db.Beneficiarios.Add(beneficiario);
                db.SaveChanges();
                return Json(new { success = true, id = beneficiario.EmpleadoId });
            }

            return PartialView("_CreaBeneficiario", beneficiario);
        }

        // GET: Beneficiarios/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Beneficiario beneficiario = db.Beneficiarios.Find(id);
            if (beneficiario == null)
            {
                return HttpNotFound();
            }
            return PartialView("_CreaBeneficiario", beneficiario);
        }

        // POST: Beneficiarios/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BeneficiarioId,NombreCompleto,Porcentaje,EmpleadoId")] Beneficiario beneficiario)
        {
            if (ModelState.IsValid)
            {
                db.Entry(beneficiario).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new { success = true, id = beneficiario.EmpleadoId });
            }
            return PartialView("_CreaBeneficiario", beneficiario);
        }

        // GET: Beneficiarios/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Beneficiario beneficiario = db.Beneficiarios.Find(id);
            if (beneficiario == null)
            {
                return HttpNotFound();
            }
            return PartialView("_EliminaBeneficiario", beneficiario);
        }

        // POST: Beneficiarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed([Bind(Include = "BeneficiarioId,NombreCompleto,Porcentaje,EmpleadoId")] Beneficiario beneficiario)
        {
            Beneficiario bdbeneficiario = db.Beneficiarios.Find(beneficiario.BeneficiarioId);
            db.Beneficiarios.Remove(bdbeneficiario);
            db.SaveChanges();
            return Json(new { success = true, id = beneficiario.EmpleadoId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EjemploAplicacionWeb/EjemploAplicacionWeb/Controllers/EmpleadosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using libNominaCurso;
using EjemploAplicacionWeb.Models;

namespace EjemploAplicacionWeb.Controllers
{
    public class EmpleadosController : Controller
    {

        private CodeFirstContexto db;
        private RepositorioEmpleado repoEmpleado;
        public EmpleadosController()
        {
            db = new CodeFirstContexto();
            repoEmpleado = new RepositorioEmpleado(db);
        }

        // GET: Empleados
        public ActionResult Index()
        {
            return View(repoEmpleado.GetEmpleados());
        }

        // GET: Empleados
        public ActionResult Busca()
        {
            BuscaEmpleadoModelView busca = new BuscaEmpleadoModelView();
            return View(busca);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult BuscaNombre([Bind(Include = "cadenaBusqueda")] 
                                            BuscaEmpleadoModelView busca)
        {
            busca.Empleados = repoEmpleado.GetEmpleados(busca.cadenaBusqueda);
            return PartialView("_ListaEmpleados", busca.Empleados);
        }

        // GET: Empleados/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empleado empleado = repoEmpleado.GetEmpleado((int)id);
            if (empleado == null)
            {
                return HttpNotFound();
            }
            return View(empleado);
        }

        // GET: Empleados/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Empleados/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EmpleadoId,Clave,Nombres,Apellidos")] Empleado empleado)
        {
            if (ModelState.IsValid)
            {
                repoEmpleado.AgregaEmpleado(empleado);
                repoEmpleado.Guardar();
                return RedirectToAction("Index");
            }

            return View(empleado);
        }

        // GET: Empleados/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empleado empleado = repoEmpleado.GetEmpleado((int)id);
            if (empleado == null)
            {
                return HttpNotFound();
            }
            return View(empleado);
        }

        // POST: Empleados/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EmpleadoId,Clave,Nombres,Apellidos")] Empleado empleado)
        {
            if (ModelState.IsValid)
            {
                repoEmpleado.ModificaEmpleado(empleado);
                repoEmpleado.Guardar();
                return RedirectToAction("Index");
            }
            return View(empleado);
        }

        // GET: Empleados/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empleado empleado = repoEmpleado.GetEmpleado((int)id);
            if (empleado == null)
            {
                return HttpNotFound();
            }
            return View(empleado);
        }

        // POST: Empleados/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            repoEmpleado.EliminaEmpleado(id);
            repoEmpleado.Guardar();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                repoEmpleado.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EjemploAplicacionWeb/EjemploAplicacionWeb/Views/Empleados/Busca.cshtml
@model EjemploAplicacionWeb.Models.BuscaEmpleadoModelView
@{
    ViewBag.Title = "Buscar empleados";
}

<h2>Buscar empleados</h2>

@using (Ajax.BeginForm("BuscaNombre", null, new AjaxOptions 
                                            {
                                                HttpMethod = "Post",
                                                LoadingElementId = "load_image",
                                                UpdateTargetId = "target_ajax",
                                                InsertionMode = InsertionMode.Replace
                                            }, 
    new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
             <div class="control-label col-md-2">Empleado a buscar:</div>
             <div class="col-md-10">
                @Html.EditorFor(model => model.cadenaBusqueda, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cadenaBusqueda, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Buscar" class="btn btn-primary" />
            </div>
        </div>
   </div>
}
<div class="container">
    <img src="~/imgs/6.gif" width="64" height="64" alt="Cargando" style="display:none" id="load_image" />
</div>
<div cass="container" id="target_ajax"></div>

EjemploAplicacionWeb/EjemploAplicacionWeb/Views/Empleados/Create.cshtml
@model libNominaCurso.Empleado

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Empleado</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Clave, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Clave, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Clave, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombres, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombres, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellidos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EjemploAplicacionWeb/EjemploAplicacionWeb/Views/Empleados/Delete.cshtml
@model libNominaCurso.Empleado

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Empleado</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Clave)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Clave)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellidos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellidos)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EjemploAplicacionWeb/EjemploAplicacionWeb/Views/Empleados/Details.cshtml
@model libNominaCurso.Empleado

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Empleado</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Clave)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Clave)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellidos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellidos)
        </dd>

    </dl>
</div>
<table class="table">
    <tr>
        <th>
            Nombre
        </th>
        <th>
            Porcentaje
        </th>
    </tr>

@foreach (var item in Model.Beneficiarios) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NombreCompleto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Porcentaje)
        </td>
    </tr>
}

</table>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.EmpleadoId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

EjemploAplicacionWeb/EjemploAplicacionWeb/Views/Empleados/Edit.cshtml
@model libNominaCurso.Empleado

@{
    ViewBag.Title = "Edit";
    string referencia = "/Beneficiarios/Create/" + Model.EmpleadoId.ToString();
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Empleado</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.EmpleadoId)

        <div class="form-group">
            @Html.LabelFor(model => model.Clave, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Clave, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Clave, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombres, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombres, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellidos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<!-- Button trigger modal -->
<p>
    <a class="btn btn-default" data-target="#modal-crear" data-toggle="modal"
       href=@referencia>Crear nueva</a>
</p>
<hr />

<div class="modal fade" id="modal-crear" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
</div>
        <table class="table">
            <tr>
                <th>Nombre</th>
                <th>Porcentaje</th>
                <th>Opciones</th>
            </tr>
            @foreach (var item in Model.Beneficiarios)
            {
                <tr>
                    <td>@item.NombreCompleto</td>
                    <td>@item.Porcentaje</td>
                    <td>
                        <a href="@Url.Action("Edit", "Beneficiarios", new { id = item.BeneficiarioId })" class="btn btn-primary"
                           data-toggle="modal" title="Edita beneficiario" data-target="#modal-crear">
                            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                        </a>
                        <a href="@Url.Action("Delete", "Beneficiarios", new { id = item.BeneficiarioId })" class="btn btn-primary"
                           data-toggle="modal" title="Eliminar beneficario" data-target="#modal-crear">
                            <span class="glyphicon glyphicon-trash aria-hidden=" true"></span>
                        </a>
                    </td>
                </tr>
            }
        </table>
        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
 <script>
    function CierraModal(data) {
        var $referencia = '/Empleados/Edit/' + data.id;
        if (data.success) {
            $('#modal-crear').modal('hide');
            window.location.href = $referencia;
        }
    }
</script>
       }

EjemploAplicacionWeb/EjemploAplicacionWeb/Views/Empleados/Index.cshtml
@model IEnumerable<libNominaCurso.Empleado>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Clave)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nombres)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Apellidos)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Clave)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nombres)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Apellidos)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.EmpleadoId }) |
            @Html.ActionLink("Details", "Details", new { id=item.EmpleadoId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.EmpleadoId })
        </td>
    </tr>
}

</table>

EjemploAplicacionWeb/EjemploAplicacionWeb/Views/Empleados/_ListaEmpleados.cshtml
@model IEnumerable<libNominaCurso.Empleado>

<table class="table">
    <tr>
        <th>Clave</th>
        <th>Nombres</th>
        <th>Opciones</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Clave)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NombreCompleto)
            </td>
            <td>
                <a href="@Url.Action("Edit", new { id = item.EmpleadoId })" class="btn btn-default"
                   data-toggle="tooltip" title="Edita empleado">
                    <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                </a>
                <a href="@Url.Action("Details", new { id = item.EmpleadoId })" class="btn btn-default"
                   data-toggle="tooltip" title="Detalle del empleado">
                    <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                </a>
                <a href="@Url.Action("Delete", new { id = item.EmpleadoId })" class="btn btn-default"
                   data-toggle="tooltip" title="Eliminar empleado">
                    <span class="glyphicon glyphicon-trash aria-hidden=" true"></span>
                </a>
            </td>
        </tr>
    }
</table>